version: '3'

networks:
  monet_network:
    external: true

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/postgres/data
      o: bind
  postgres-config:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/postgres/config
      o: bind
  postgres-logs:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/postgres/logs
      o: bind

services:
  postgres:
    restart: always
    privileged: true
    image: registry.cn-beijing.aliyuncs.com/monet/postgres:16.1
    container_name: postgres
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_postgres_password
      POSTGRES_DB: postgres
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-config:/var/lib/postgresql/config
      - postgres-logs:/var/lib/postgresql/logs
    secrets:
      - postgres_postgres_password
    command: postgres -c config_file=/var/lib/postgresql/config/postgres.conf
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
        max-file: "10"
    ports:
      - "15432:5432"
    networks:
      monet_network:
        ipv4_address: 172.16.0.6

secrets:
  postgres_postgres_password:
    file: /opt/docker/secrets/postgres_postgres_password.txt