# 选择基础镜像
FROM openjdk:8u342-jdk

ARG DORIS_VERSION="1.2.7.1"

# 设置环境变量
ENV JAVA_HOME="/usr/local/openjdk-8" \
    PATH="/opt/apache-doris/be/bin:$PATH" \
    DEBIAN_FRONTEND=noninteractive

# 下载软件至镜像内，可根据需要替换
#ADD ./resource/apache-doris-be-${x.x.x}-bin-x86_64.tar.gz /opt/

# https://apache-doris-releases.oss-accelerate.aliyuncs.com/apache-doris-1.2.7.1-bin-x64.tar.xz
RUN apt-get update && \
    apt-get install -y default-mysql-client wget vim curl net-tools && \
    apt-get clean && \
    wget -qO /opt/apache-doris-bin-x64.tar.gz https://apache-doris-releases.oss-accelerate.aliyuncs.com/apache-doris-${DORIS_VERSION}-bin-x64.tar.xz && \
    tar -xf /opt/apache-doris-bin-x64.tar.gz -C /opt/ && \
    cd /opt && \
    mv /opt/apache-doris-${DORIS_VERSION}-bin-x64 /opt/apache-doris && \
    mv /opt/apache-doris/be/bin/start_be.sh /opt/apache-doris/be/bin/start_be_bak.sh && \
    rm -rf /opt/apache-doris-bin-x64.tar.gz /opt/apache-doris/extensions /opt/apache-doris/fe

COPY ./src/doris-be/*.sh /opt/apache-doris/be/bin
RUN chmod 755 /opt/apache-doris/be/bin/init_be.sh && \
    chmod 755 /opt/apache-doris/be/bin/start_be.sh && \
    chmod 755 /opt/apache-doris/be/bin/cancel_be.sh

ENTRYPOINT ["/opt/apache-doris/be/bin/init_be.sh"]